### ISSUE TITLE
Plugin cannot list episodes anymore

### ISSUE THREAD

**Issue by agrohn** [finnhubb/plugin.video.areena#2]
When trying to get episodes, plugin fails with `403 forbidden` . `kodi.log` shows following:

```
2022-06-30 10:01:42.839 T:1729    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'requests.exceptions.HTTPError'>
                                                   Error Contents: 403 Client Error: Forbidden for url: https://programs.api.yle.fi/v3/schema/v1/series/1-2166614/episodes?prog
ram_type=program&order=natural:asc&app_id=areena_web_frontend_prod&app_key=4622a8f8505bb056c956832a70c105d4&&limit=100&offset=0
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.areena/addon.py", line 11, in <module>
                                                       addon_areena_main(sys.argv[2][1:])
                                                     File "/storage/.kodi/addons/plugin.video.areena/resources/lib/router.py", line 66, in addon_areena_main
                                                       try_cache(param_string, locale) or show_remote_list(event_type, params, param_string, locale)
                                                     File "/storage/.kodi/addons/plugin.video.areena/resources/lib/router.py", line 174, in show_remote_list
                                                       content = get_episodes(yle_id, locale)
                                                     File "/storage/.kodi/addons/plugin.video.areena/resources/lib/router.py", line 231, in get_episodes
                                                       return get_extended_content(url, locale, offset=0, total=2000, parser="episodes")
                                                     File "/storage/.kodi/addons/plugin.video.areena/resources/lib/router.py", line 241, in get_extended_content
                                                       res = get_url_response(url)
                                                     File "/storage/.kodi/addons/plugin.video.areena/resources/lib/network.py", line 42, in get_url_response
                                                       res.raise_for_status()
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 960, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://programs.api.yle.fi/v3/schema/v1/series/1-216661
4/episodes?program_type=program&order=natural:asc&app_id=areena_web_frontend_prod&app_key=4622a8f8505bb056c956832a70c105d4&&limit=100&offset=0
                                                   -->End of Python script error report<--
```

Apparently  `programs.api.yle.fi` is not open to public web anymore.

**Comment by finnhubb** [comment]
Hi @agrohn,

Thanks for reporting this issue.

I switched to a different api and seems to mostly work. There is minor issue with some clips not displaying. Try latest release and let me know if you notice anything else.

Enjoy!

**Comment by agrohn** [comment]
Thanks, updated to `v1.2.0` and it works like a charm!

**Comment by Mateus109** [comment]
Works outside of Finland too, amazing!
